=== benaissanadim/SI4-Modelisation_XML/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.1">

<xs:element name="ORGANISME" type="ORGANISME_TYPE"/>

<xs:complexType name="ORGANISME_TYPE">
    <xs:sequence>
        <xs:element name="AGENCES" maxOccurs="1" minOccurs="1">
            <xs:complexType>
              <xs:sequence>
                <xs:element type="AGENCE_TYPE" name="AGENCE" maxOccurs="unbounded" minOccurs="0"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        <xs:element name="CLIENTS" maxOccurs="1" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element type="CLIENT_TYPE" name="CLIENT" maxOccurs="unbounded" minOccurs="1"/>
              </xs:sequence>
            </xs:complexType>
        </xs:element>
        <xs:element name="LANGUES" maxOccurs="1" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element type="LANGUE_TYPE" name="LANGUE" maxOccurs="unbounded" minOccurs="0"/>
              </xs:sequence>
            </xs:complexType>
        </xs:element>
        <xs:element name="DESTINATIONS" maxOccurs="1" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element type="DESTINATION_TYPE" name="DESTINATION" maxOccurs="unbounded" minOccurs="0"/>
              </xs:sequence>
            </xs:complexType>
        </xs:element>
    </xs:sequence>
</xs:complexType>




<xs:complexType name="AGENCE_TYPE">
    <xs:sequence>
      <xs:element name="NOM" type="xs:string"/>
      <xs:element name="ADRESSE" type="ADRESSE_TYPE"/>

        <xs:element name="SEJOURS" maxOccurs="1" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element type="SEJOUR_TYPE" name="SEJOUR" maxOccurs="unbounded" minOccurs="0"/>
              </xs:sequence>
            </xs:complexType>
        </xs:element>
        <xs:element name="ENSEIGNANTS" maxOccurs="1" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element type="ENSEIGNANT_TYPE" name="ENSEIGNANT" maxOccurs="unbounded" minOccurs="0"/>
              </xs:sequence>
            </xs:complexType>
        </xs:element>
        <xs:element name="ACCOMPAGNATEURS" maxOccurs="1" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element type="ACCOMPAGNATEUR_TYPE" name="ACCOMPAGNATEUR" maxOccurs="unbounded" minOccurs="0"/>
              </xs:sequence>
            </xs:complexType>
        </xs:element>
    </xs:sequence>
</xs:complexType>


<xs:complexType name="SEJOUR_TYPE">
  <xs:sequence>
    <xs:element name="NOM" type="xs:string"/>
    <xs:element name="TYPES_PUBLIC" maxOccurs="1" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element type="TYPE_PUBLIC_TYPE" name="TYPE_PUBLIC" maxOccurs="unbounded" minOccurs="0"/>
          </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="DESCRIPTION" type="xs:string"/>
    <xs:element name="TARIF" type="MONEY_TYPE" />
    <xs:element name="ACTIVITEES" maxOccurs="1" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element type="ACTIVITEE_TYPE" name="ACTIVITEE" maxOccurs="unbounded" minOccurs="0"/>
          </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="SESSIONS" maxOccurs="1" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element type="SESSION_TYPE" name="SESSION" maxOccurs="unbounded" minOccurs="0"/>
          </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="DESTINATIONS" maxOccurs="1" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element type="REF_TYPE" name="DESTINATION_REF" maxOccurs="unbounded" minOccurs="0"/>
          </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="LANGUES_ENSEIGNEES" maxOccurs="1" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element type="LANGUE_ENSEIGNEE_TYPE" name="LANGUE_ENSEIGNEE" maxOccurs="unbounded" minOccurs="0"/>
          </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="LISTE_AVIS" maxOccurs="1" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element type="AVIS_TYPE" name="AVIS" maxOccurs="unbounded" minOccurs="0"/>
          </xs:sequence>
        </xs:complexType>
    </xs:element>
  </xs:sequence>
  <xs:attribute type="TYPE_SEJOUR_TYPE" name="type" use="required"/>
</xs:complexType>



<xs:simpleType name="MONEY_TYPE">
    <xs:restriction base="xs:string">
      <xs:pattern value="\d+\$"/>
    </xs:restriction>
  </xs:simpleType>


<xs:complexType name="CLIENT_TYPE">
  <xs:sequence>
    <xs:element name="NOM" type="NAME_TYPE"/>
    <xs:element name="PRENOM" type="NAME_TYPE"/>
  </xs:sequence>
  <xs:attribute name="id" use="required">
    <xs:simpleType>
      <xs:restriction base="xs:ID">
        <xs:pattern value="cl_.*"/>
      </xs:restriction>
    </xs:simpleType>
    </xs:attribute>
</xs:complexType>

<xs:complexType name="ENSEIGNANT_TYPE">
  <xs:sequence>
    <xs:element name="NOM" type="NAME_TYPE"/>
    <xs:element name="PRENOM" type="NAME_TYPE"/>
    <xs:element name="EMAIL" type="EMAIL_TYPE"/>
    <xs:element name="ENSEIGNEMENTS" minOccurs="0" maxOccurs="1">
      <xs:complexType>
        <xs:sequence>
          <xs:element name="LANGUE_REF" type="REF_TYPE" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:complexType>
    </xs:element>
  </xs:sequence>
  <xs:attribute name="id" use="required">
    <xs:simpleType>
      <xs:restriction base="xs:ID">
        <xs:pattern value="e_.*"/>
      </xs:restriction>
    </xs:simpleType>
    </xs:attribute></xs:complexType>

<xs:complexType name="ACCOMPAGNATEUR_TYPE">
  <xs:sequence>
    <xs:element name="NOM" type="NAME_TYPE"/>
    <xs:element name="PRENOM" type="NAME_TYPE"/>
    <xs:element name="EMAIL" type="EMAIL_TYPE"/>
  </xs:sequence>
  <xs:attribute name="id" use="optional">
    <xs:simpleType>
      <xs:restriction base="xs:ID">
        <xs:pattern value="a_.*"/>
      </xs:restriction>
    </xs:simpleType>
    </xs:attribute>
  </xs:complexType>

<xs:simpleType name="EMAIL_TYPE">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"/>
    </xs:restriction>
  </xs:simpleType>

<xs:simpleType name="NAME_TYPE">
    <xs:restriction base="xs:string">
      <xs:minLength value="3"/>
      <xs:maxLength value="20"/>
    </xs:restriction>
  </xs:simpleType>

  
  <xs:complexType name="SESSION_TYPE">
    <xs:sequence>
        <xs:element name="DEBUT" type="xs:date"/>
        <xs:element name="FIN" type="xs:date"/>
        <xs:element name="PARTICIPANTS" type="PARTICIPANTS_TYPE"/>
    </xs:sequence>
    <xs:attribute name="id" use="optional">
      <xs:simpleType>
        <xs:restriction base="xs:ID">
          <xs:pattern value="s_.*"/>
        </xs:restriction>
      </xs:simpleType>
      </xs:attribute>
  </xs:complexType>

  <xs:complexType name="PARTICIPANTS_TYPE">
    <xs:sequence>
      <xs:element name="PERSONNELS" type="PERSONNELS_TYPE" minOccurs="0"/>
      <xs:element name="CLIENTS" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="CLIENT_REF" type="REF_TYPE" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueClientId">
          <xs:selector xpath="./CLIENT_REF"/>
          <xs:field xpath="@idref"/>
        </xs:unique>
      </xs:element>
    </xs:sequence>
  </xs:complexType>



  <xs:complexType name="PERSONNELS_TYPE">
    <xs:sequence>
      <xs:element name="ENSEIGNANTS" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="ENSEIGNANT_REF" type="REF_TYPE" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueEnseignantId">
          <xs:selector xpath="./ENSEIGNANT_REF"/>
          <xs:field xpath="@idref"/>
        </xs:unique>
      </xs:element>
      <xs:element name="ACCOMPAGNATEURS" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="ACCOMPAGNATEUR_REF" type="REF_TYPE" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueAccompagnateurtId">
          <xs:selector xpath="./ACCOMPAGNATEUR_REF"/>
          <xs:field xpath="@idref"/>
        </xs:unique>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="CLIENTS_TYPE">
    <xs:sequence>
      <xs:element name="CLIENT" type="REF_TYPE" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="REF_TYPE">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:IDREF" name="idref" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="DESTINATION_REF_TYPE">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="idref" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

<xs:complexType name="LANGUE_TYPE">
      <xs:sequence>
        <xs:element name="NOM" type="NAME_TYPE"/>
        <xs:element name="NIVEAU">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="A1"/>
                    <xs:enumeration value="A2"/>
                    <xs:enumeration value="B1"/>
                    <xs:enumeration value="B2"/>
                    <xs:enumeration value="C1"/>
                    <xs:enumeration value="C2"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="id" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:ID">
            <xs:pattern value="l_.*"/>
          </xs:restriction>
        </xs:simpleType>
        </xs:attribute>
 </xs:complexType>

 <xs:complexType name="DESTINATION_TYPE">
    <xs:sequence>
      <xs:element name="VILLE" type="NAME_TYPE" />
      <xs:element name="PAYS" type="NAME_TYPE"/>
    </xs:sequence>
    <xs:attribute name="id" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:ID">
          <xs:pattern value="d_.*"/>
        </xs:restriction>
      </xs:simpleType>
      </xs:attribute>  </xs:complexType>


  <xs:complexType name="ACTIVITEE_TYPE">
    <xs:sequence>
      <xs:element name="DESCRIPTION" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="type" type="TYPE_ACTIVITE_TYPE"/>
  </xs:complexType>

  <xs:simpleType name="TYPE_ACTIVITE_TYPE">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Sport"/>
      <xs:enumeration value="Culture"/>
      <xs:enumeration value="Loisir"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TYPE_SEJOUR_TYPE">
    <xs:restriction base="xs:string">
      <xs:enumeration value="colonies de vacances"/>
      <xs:enumeration value="groupes scolaires"/>
      <xs:enumeration value="immersions en famille"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TYPE_PUBLIC_TYPE">
    <xs:restriction base="xs:string">
      <xs:enumeration value="adultes"/>
      <xs:enumeration value="enfants"/>
      <xs:enumeration value="familles"/>
      <xs:enumeration value="adolescents"/>
    </xs:restriction>
  </xs:simpleType>


  <xs:complexType name="AVIS_TYPE">
    <xs:sequence>
      <xs:element name="NOTE" type="NOTE_TYPE"/>
      <xs:element name="COMMENTAIRE" type="xs:string"/>
      <xs:element name="DATE" type="xs:date"/>
      <xs:element name="SESSION_REF" type="REF_TYPE"/>
      <xs:element name="CLIENT_REF" type="REF_TYPE"/>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="NOTE_TYPE">
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="10"/>
    </xs:restriction>
  </xs:simpleType>


  
  <xs:complexType name="TEST_TYPE">
    <xs:sequence>
        <xs:element name="NOM" type="xs:string"/>
      <xs:element name="QUESTIONS" type="QUESTIONS_TYPE"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="QUESTIONS_TYPE">
    <xs:sequence>
  <xs:element name="QUESTION" maxOccurs="unbounded">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="CONTENU" type="xs:string"/>
        
        <xs:element name="LISTE_CHOIX" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="CHOIX" type="xs:string" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
          <xs:unique name="uniqueChoix">
            <xs:selector xpath="./CHOIX"/>
            <xs:field xpath="."/>
          </xs:unique>
        </xs:element>
        <xs:element name="POINTS" type="xs:integer"/>
        <xs:element name="CHAPITRE_REF" type="REF_TYPE"/>
      </xs:sequence>
      
      <xs:attribute name="type">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="libre"/>
            <xs:enumeration value="avec choix"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
</xs:sequence>
</xs:complexType>

  
<xs:complexType name="CHAPITRE_TYPE">
  <xs:sequence>
    <xs:element name="TITRE" type="xs:string"/>
    <xs:element name="CONTENU" type="xs:string"/>
  </xs:sequence>
  <xs:attribute name="id" use="required">
    <xs:simpleType>
      <xs:restriction base="xs:ID">
        <xs:pattern value="c_.*"/>
      </xs:restriction>
    </xs:simpleType>
    </xs:attribute>
</xs:complexType>

<xs:complexType name="COURS_TYPE">
    <xs:sequence>
        <xs:element name="NOM" type="xs:string"/>
        <xs:element name="CHAPITRES" maxOccurs="1" minOccurs="1">
            <xs:complexType>
              <xs:sequence>
                <xs:element type="CHAPITRE_TYPE" name="CHAPITRE" maxOccurs="unbounded" minOccurs="0"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
</xs:complexType>

<xs:complexType name="LANGUE_ENSEIGNEE_TYPE">
    <xs:sequence>
        <xs:element name="COURS" type="COURS_TYPE"></xs:element>
        <xs:element name="TEST" type="TEST_TYPE"></xs:element>
    </xs:sequence>
    <xs:attribute type="xs:IDREF" name="idref" use="required"/>
</xs:complexType>

<xs:complexType name="ADRESSE_TYPE">
      <xs:sequence>
        <xs:element name="AVENUE" type="xs:string"/>
        <xs:element name="CODE_POSTAL" type="xs:string"/>
        <xs:element name="VILLE" type="xs:string"/>
        <xs:element name="PAYS" type="xs:string"/>
      </xs:sequence>
</xs:complexType>  


<!-- to verify -->
<xs:element name="validatoe">
<xs:key name="chapitreKey">
  <xs:selector xpath="CHAPITRE"/>
  <xs:field xpath="@id" />
</xs:key>
<xs:keyref name="chapitreRef" refer="chapitreKey">
  <xs:selector xpath="CHAPITRE_REF"/>
  <xs:field xpath="@idRef"/>
</xs:keyref>
</xs:element>
<!-- to verify -->

</xs:schema>

=== benaissanadim/SI4-Modelisation_XML/projet.xml
<?xml version="1.0" encoding="UTF-8"?>
<ORGANISME xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
    <AGENCES>
    <AGENCE>
        <NOM>Club aventure</NOM>
        <ADRESSE>
            <AVENUE>67 Rue Saint-Jacques</AVENUE>
            <CODE_POSTAL>75005</CODE_POSTAL>
            <VILLE>PARIS</VILLE>
            <PAYS>FRANCE</PAYS>
        </ADRESSE>
        <SEJOURS>
            <SEJOUR type="colonies de vacances">
                <NOM>Séjour au japan</NOM>
                <TYPES_PUBLIC>
                    <TYPE_PUBLIC>adultes</TYPE_PUBLIC>
                    <TYPE_PUBLIC>adolescents</TYPE_PUBLIC>
                </TYPES_PUBLIC>
                <DESCRIPTION>Venez améliorer votre niveau de japonais et découvrir la culture japonaise lors de notre colonie de vacances à Tokyo ! 
                    &#xA; Pendant deux semaines, vous suivrez des cours de japonais le matin et participerez à des activités culturelles l'après-midi. &#xA; Logement en chambres partagées, encadrement assuré pour les jeunes de 14 à 18 ans. Inscrivez-vous dès maintenant !</DESCRIPTION>
                <TARIF>500$</TARIF>
                <ACTIVITEES>
                    <ACTIVITEE type="Sport">
                        <DESCRIPTION>Initiation à l'aïkido, art martial japonais basé sur la défense et le contrôle de l'adversaire</DESCRIPTION>
                    </ACTIVITEE>
                    <ACTIVITEE type="Sport">
                        <DESCRIPTION>Randonnée dans les montagnes environnantes de Tokyo pour profiter de la nature et de la vue sur la ville</DESCRIPTION>
                    </ACTIVITEE>
                    <ACTIVITEE type="Culture">
                        <DESCRIPTION>Atelier de calligraphie japonaise pour apprendre à écrire des kanjis (caractères japonais)</DESCRIPTION>
                    </ACTIVITEE>
                    <ACTIVITEE type="Culture">
                        <DESCRIPTION>Visite du musée Edo-Tokyo pour découvrir l'histoire de Tokyo</DESCRIPTION>
                    </ACTIVITEE>
                </ACTIVITEES>
                <SESSIONS>
                    <SESSION id="s_1">
                        <DEBUT>2023-03-30</DEBUT>
                        <FIN>2023-04-15</FIN>
                        <PARTICIPANTS>
                            <PERSONNELS>
                                <ENSEIGNANTS>
                                    <ENSEIGNANT_REF idref="e_1" />
                                    <ENSEIGNANT_REF idref="e_2" />
                                </ENSEIGNANTS>
                                <ACCOMPAGNATEURS>
                                    <ACCOMPAGNATEUR_REF idref="a_1"/>
                                    <ACCOMPAGNATEUR_REF idref="a_2" />
                                </ACCOMPAGNATEURS>
                            </PERSONNELS>
                            <CLIENTS>
                               <CLIENT_REF idref="cl_1"/> 
                               <CLIENT_REF idref="cl_2"/> 
                               <CLIENT_REF idref="cl_3"/> 
                               <CLIENT_REF idref="cl_4"/> 
                               <CLIENT_REF idref="cl_5"/> 
                               <CLIENT_REF idref="cl_6"/> 
                               <CLIENT_REF idref="cl_7"/> 
                               <CLIENT_REF idref="cl_8"/> 
                               <CLIENT_REF idref="cl_9"/> 
                               <CLIENT_REF idref="cl_10"/> 
                            </CLIENTS>
                        </PARTICIPANTS>
                    </SESSION>
                    <SESSION id="s_2">
                      <DEBUT>2023-01-03</DEBUT>
                      <FIN>2023-01-15</FIN>
                      <PARTICIPANTS>
                          <PERSONNELS>
                              <ENSEIGNANTS>
                                  <ENSEIGNANT_REF idref="e_3" />
                              </ENSEIGNANTS>
                              <ACCOMPAGNATEURS>
                                  <ACCOMPAGNATEUR_REF idref="a_3"/>
                                  <ACCOMPAGNATEUR_REF idref="a_4" />
                              </ACCOMPAGNATEURS>
                          </PERSONNELS>
                          <CLIENTS>
                            <CLIENT_REF idref="cl_6"/> 
                            <CLIENT_REF idref="cl_7"/> 
                            <CLIENT_REF idref="cl_8"/> 
                            <CLIENT_REF idref="cl_9"/> 
                            <CLIENT_REF idref="cl_10"/> 
                            <CLIENT_REF idref="cl_11"/> 
                            <CLIENT_REF idref="cl_12"/> 
                            <CLIENT_REF idref="cl_13"/> 
                            <CLIENT_REF idref="cl_14"/> 
                            <CLIENT_REF idref="cl_15"/> 
                          </CLIENTS>
                      </PARTICIPANTS>
                  </SESSION>
                </SESSIONS>
                <DESTINATIONS>
                    <DESTINATION_REF idref="d_2" />
                </DESTINATIONS>
                <LANGUES_ENSEIGNEES>
                    <LANGUE_ENSEIGNEE idref="l_8">
                        <COURS>
                            <NOM>Initiation à la langue japonaise : Ecrit ET Oral</NOM>
                            <CHAPITRES>
                                <CHAPITRE id="c_1">
                                    <TITRE>initiation aux lettres japonais</TITRE>
                                    <CONTENU> Les lettres japonaises comprennent trois types d'écriture : les kanjis, les hiraganas et les katakanas. 
                                        Les kanjis sont des caractères d'origine chinoise qui représentent des mots ou des idées, tandis que les hiraganas et les katakanas sont des syllabaires japonais. 
                                        Les hiraganas sont utilisés pour les mots courants, tandis que les katakanas sont souvent utilisés pour les mots étrangers ou pour transcrire des noms propres.
                                         L'initiation aux lettres japonaises peut inclure l'apprentissage de l'alphabet hiragana et katakana, 
                                         ainsi que la pratique de l'écriture des kanjis.</CONTENU>
                                </CHAPITRE>
                                <CHAPITRE id="c_2">
                                    <TITRE>communication</TITRE>
                                    <CONTENU> Pour bien communiquer en japonais, il est important d'apprendre les expressions courantes utilisées dans la vie quotidienne et de comprendre les particularités de la langue japonaise. 
                                        Par exemple, au Japon, il est courant d'utiliser des suffixes pour montrer le niveau de respect ou d'affection que l'on porte à une personne. 
                                        Ainsi, on peut ajouter le suffixe "-san" après le nom d'une personne pour montrer du respect, ou le suffixe "-chan" pour montrer de l'affection.</CONTENU>
                                </CHAPITRE>
                            </CHAPITRES>
                        </COURS>
                        <TEST>
                            <NOM> test de niveau Japonais pour les débutants</NOM>
                            <QUESTIONS>
                                <QUESTION type ="avec choix">
                                    <CONTENU>Quel est le nom des trois types d'écriture utilisés en japonais ?</CONTENU>
                                    <LISTE_CHOIX>
                                        <CHOIX>Kanjis, hiraganas, katakanas</CHOIX>
                                        <CHOIX> Romajis, hiraganas, katakanas</CHOIX>
                                        <CHOIX>Kanjis, romajis, hiraganas</CHOIX>
                                    </LISTE_CHOIX>
                                    <POINTS>5</POINTS>
                                    <CHAPITRE_REF idref="c_1" />
                                </QUESTION>
                                <QUESTION type="libre">
                                   <CONTENU>Quels sont les expressions courantes en japonais ?</CONTENU>
                                    <POINTS>5</POINTS>
                                    <CHAPITRE_REF idref="c_1"/>
                                </QUESTION>
                            </QUESTIONS>
                        </TEST>
                    </LANGUE_ENSEIGNEE>
                </LANGUES_ENSEIGNEES>
                <LISTE_AVIS>
                    <AVIS>
                        <NOTE>10</NOTE>
                        <COMMENTAIRE>EXCELLENT VOYAGE</COMMENTAIRE>
                        <DATE>2020-10-10</DATE>
                        <SESSION_REF idref="s_1" />
                        <CLIENT_REF idref="cl_1"></CLIENT_REF>
                    </AVIS>
                    <AVIS>
                      <NOTE>8</NOTE>
                      <COMMENTAIRE>WOW !!</COMMENTAIRE>
                      <DATE>2020-10-11</DATE>
                      <SESSION_REF idref="s_1" />
                      <CLIENT_REF idref="cl_2"></CLIENT_REF>
                  </AVIS>
                </LISTE_AVIS>
            </SEJOUR>

            <SEJOUR type="groupes scolaires">
            <NOM>Séjour en Italie</NOM>
              <TYPES_PUBLIC>
                  <TYPE_PUBLIC>adolescents</TYPE_PUBLIC>
                  <TYPE_PUBLIC>adultes</TYPE_PUBLIC>
              </TYPES_PUBLIC>
              <DESCRIPTION>Partez en séjour linguistique en Italie pour apprendre l'italien dans deux villes magnifiques : Milan et Rome ! 
                Ce séjour est spécialement conçu pour les étudiants qui souhaitent améliorer leur niveau d'italien tout en découvrant la culture italienne.
